export enum API_ERROR {
  INPUT_TEXT_TOO_SHORT = "INPUT_TEXT_TOO_SHORT",
  INPUT_TEXT_TOO_LONG = "INPUT_TEXT_TOO_LONG",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
}
